// @generated by protoc-gen-es v2.9.0 with parameter "target=ts,import_extension=js"
// @generated from file auth/v1/auth.proto (package auth.v1, edition 2023)
// option features.field_presence = IMPLICIT;
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/auth.proto.
 */
export const file_auth_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL2F1dGgucHJvdG8SB2F1dGgudjEiMwoNU2lnbkluUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSIfCg5TaWduSW5SZXNwb25zZRINCgV0b2tlbhgBIAEoCTJKCgtBdXRoU2VydmljZRI7CgZTaWduSW4SFi5hdXRoLnYxLlNpZ25JblJlcXVlc3QaFy5hdXRoLnYxLlNpZ25JblJlc3BvbnNlIgBCRVo+Z2l0aHViLmNvbS9maXZlYml0c2lvL2NvdHRvbi9pbnRlcm5hbC9nZW4vcHJvdG8vYXV0aC92MTthdXRodjGSAwIIAmIIZWRpdGlvbnNw6Ac");

/**
 * @generated from message auth.v1.SignInRequest
 */
export type SignInRequest = Message<"auth.v1.SignInRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.v1.SignInRequest.
 * Use `create(SignInRequestSchema)` to create a new message.
 */
export const SignInRequestSchema: GenMessage<SignInRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 0);

/**
 * @generated from message auth.v1.SignInResponse
 */
export type SignInResponse = Message<"auth.v1.SignInResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message auth.v1.SignInResponse.
 * Use `create(SignInResponseSchema)` to create a new message.
 */
export const SignInResponseSchema: GenMessage<SignInResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 1);

/**
 * web facing
 *
 * @generated from service auth.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc auth.v1.AuthService.SignIn
   */
  signIn: {
    methodKind: "unary";
    input: typeof SignInRequestSchema;
    output: typeof SignInResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth_v1_auth, 0);

