package apperr

// Orgs domain reasons.
var (
	ReasonOrgNotFound              = codes.add("ORG_NOT_FOUND")
	ReasonOrgNotAMember            = codes.add("ORG_NOT_A_MEMBER")
	ReasonOrgAdminRequired         = codes.add("ORG_ADMIN_REQUIRED")
	ReasonOrgRoleForbidden         = codes.add("ORG_ROLE_FORBIDDEN")
	ReasonOrgMemberNotFound        = codes.add("ORG_MEMBER_NOT_FOUND")
	ReasonOrgMemberAlreadyExists   = codes.add("ORG_MEMBER_ALREADY_EXISTS")
	ReasonOrgCannotRemoveSelf      = codes.add("ORG_CANNOT_REMOVE_SELF")
	ReasonOrgUnsupportedRole       = codes.add("ORG_UNSUPPORTED_ROLE")
	ReasonCannotRemoveLastAdmin    = codes.add("CANNOT_REMOVE_LAST_ADMIN")
	ReasonCannotDemoteLastAdmin    = codes.add("CANNOT_DEMOTE_LAST_ADMIN")
	ReasonCannotLeaveAsLastMember  = codes.add("CANNOT_LEAVE_AS_LAST_MEMBER")
	ReasonInvitationNotFound       = codes.add("INVITATION_NOT_FOUND")
	ReasonInvitationNotPending     = codes.add("INVITATION_NOT_PENDING")
	ReasonInvitationExpired        = codes.add("INVITATION_EXPIRED")
	ReasonInvitationAlreadyPending = codes.add("INVITATION_ALREADY_PENDING")
	ReasonInvitationWrongEmail     = codes.add("INVITATION_WRONG_EMAIL")
	ReasonInvitationSendLimit      = codes.add("INVITATION_SEND_LIMIT")
	ReasonProjectNameTaken         = codes.add("PROJECT_NAME_TAKEN")

	ReasonOrgCreationRestricted    = codes.add("ORG_CREATION_RESTRICTED")
	ReasonDomainInvalid            = codes.add("DOMAIN_INVALID")
	ReasonDomainNotFound           = codes.add("DOMAIN_NOT_FOUND")
	ReasonDomainLimitReached       = codes.add("DOMAIN_LIMIT_REACHED")
	ReasonDomainNotVerified        = codes.add("DOMAIN_NOT_VERIFIED")
	ReasonDomainVerificationFailed = codes.add("DOMAIN_VERIFICATION_FAILED")
	ReasonDomainLookupFailed       = codes.add("DOMAIN_LOOKUP_FAILED")
	ReasonDomainSSONotSeen         = codes.add("DOMAIN_SSO_NOT_SEEN")
)
